In [ ]:
import pandas as pd
import numpy as np
# Data preprocessing

# Read data
data = pd.read_csv("Mall_Customers.csv")    # reading the main csv
data.to_csv("Result.csv")        # copying the csv
df = pd.DataFrame(data)          # data ko csv se df

print(df.info)

<bound method DataFrame.info of      CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]>

In [ ]:
df.isnull() # checking null values

     CustomerID  Genre    Age  Annual Income (k$)  Spending Score (1-100)
0         False  False  False               False                   False
1         False  False  False               False                   False
2         False  False  False               False                   False
3         False  False  False               False                   False
4         False  False  False               False                   False
..          ...    ...    ...                 ...                     ...
195       False  False  False               False                   False
196       False  False  False               False                   False
197       False  False  False               False                   False
198       False  False  False               False                   False
199       False  False  False               False                   False

[200 rows x 5 columns]

In [4]:
df.isnull().sum()

CustomerID                0
Genre                     0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [19]:
df.loc[0,"Age"] = np.nan    # creating null value

In [9]:
df.isnull()

     CustomerID  Genre    Age  Annual Income (k$)  Spending Score (1-100)
0         False  False   True               False                   False
1         False  False  False               False                   False
2         False  False  False               False                   False
3         False  False  False               False                   False
4         False  False  False               False                   False
..          ...    ...    ...                 ...                     ...
195       False  False  False               False                   False
196       False  False  False               False                   False
197       False  False  False               False                   False
198       False  False  False               False                   False
199       False  False  False               False                   False

[200 rows x 5 columns]

In [7]:
df.isnull().sum()

CustomerID                0
Genre                     0
Age                       1
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [20]:
df['Age'].fillna(df['Age'].mean(),inplace=True)  # handling the null value
df.to_csv("Result.csv")

C:\Users\omprk\AppData\Local\Temp\ipykernel_4152\2584986114.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)  # handling the null value

In [16]:
df.isnull().sum()

CustomerID                0
Genre                     0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [ ]:
df.duplicated()   # check for duplicates
# if duplicates hai toh ----> df.drop_duplicates()  which will drop the duplicates

0      False
1      False
2      False
3      False
4      False
       ...
195    False
196    False
197    False
198    False
199    False
Length: 200, dtype: bool

In [25]:
df.sort_values("Age",ascending=False)  # sorting based on age

     CustomerID   Genre   Age  Annual Income (k$)  Spending Score (1-100)
60           61    Male  70.0                  46                      56
70           71    Male  70.0                  49                      55
57           58    Male  69.0                  44                      46
67           68  Female  68.0                  48                      48
90           91  Female  68.0                  59                      55
..          ...     ...   ...                 ...                     ...
68           69    Male  19.0                  48                      59
114         115  Female  18.0                  65                      48
65           66    Male  18.0                  48                      59
33           34    Male  18.0                  33                      92
91           92    Male  18.0                  59                      41

[200 rows x 5 columns]

In [26]:
df[df["Age"]>60]

     CustomerID   Genre   Age  Annual Income (k$)  Spending Score (1-100)
8             9    Male  64.0                  19                       3
10           11    Male  67.0                  19                      14
40           41  Female  65.0                  38                      35
57           58    Male  69.0                  44                      46
60           61    Male  70.0                  46                      56
62           63  Female  67.0                  47                      52
64           65    Male  63.0                  48                      51
67           68  Female  68.0                  48                      48
70           71    Male  70.0                  49                      55
82           83    Male  67.0                  54                      41
90           91  Female  68.0                  59                      55
102         103    Male  67.0                  62                      59
106         107  Female  66.0                  63                      50
108         109    Male  68.0                  63                      43
109         110    Male  66.0                  63                      48
110         111    Male  65.0                  63                      52
116         117  Female  63.0                  65                      43

In [30]:
df[(df["Age"]>60) | (df["Age"]<65)]

     CustomerID   Genre        Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male  38.949749                  15                      39
1             2    Male  21.000000                  15                      81
2             3  Female  20.000000                  16                       6
3             4  Female  23.000000                  16                      77
4             5  Female  31.000000                  17                      40
..          ...     ...        ...                 ...                     ...
195         196  Female  35.000000                 120                      79
196         197  Female  45.000000                 126                      28
197         198    Male  32.000000                 126                      74
198         199    Male  32.000000                 137                      18
199         200    Male  30.000000                 137                      83

[200 rows x 5 columns]

In [ ]:
df.head() # returns first 5 rows

   CustomerID   Genre        Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male  38.949749                  15                      39
1           2    Male  21.000000                  15                      81
2           3  Female  20.000000                  16                       6
3           4  Female  23.000000                  16                      77
4           5  Female  31.000000                  17                      40

In [32]:
df.head(20)

    CustomerID   Genre        Age  Annual Income (k$)  Spending Score (1-100)
0            1    Male  38.949749                  15                      39
1            2    Male  21.000000                  15                      81
2            3  Female  20.000000                  16                       6
3            4  Female  23.000000                  16                      77
4            5  Female  31.000000                  17                      40
5            6  Female  22.000000                  17                      76
6            7  Female  35.000000                  18                       6
7            8  Female  23.000000                  18                      94
8            9    Male  64.000000                  19                       3
9           10  Female  30.000000                  19                      72
10          11    Male  67.000000                  19                      14
11          12  Female  35.000000                  19                      99
12          13  Female  58.000000                  20                      15
13          14  Female  24.000000                  20                      77
14          15    Male  37.000000                  20                      13
15          16    Male  22.000000                  20                      79
16          17  Female  35.000000                  21                      35
17          18    Male  20.000000                  21                      66
18          19    Male  52.000000                  23                      29
19          20  Female  35.000000                  23                      98

In [33]:
df.tail() # returns last 5 rows

     CustomerID   Genre   Age  Annual Income (k$)  Spending Score (1-100)
195         196  Female  35.0                 120                      79
196         197  Female  45.0                 126                      28
197         198    Male  32.0                 126                      74
198         199    Male  32.0                 137                      18
199         200    Male  30.0                 137                      83

In [ ]:
# groups ka pta lgta hai jiske liye ye attribute same hai
groups = df.groupby("Annual Income (k$)")

In [43]:
groups.groups

{15: [0, 1], 16: [2, 3], 17: [4, 5], 18: [6, 7], 19: [8, 9, 10, 11], 20: [12, 13, 14, 15], 21: [16, 17], 23: [18, 19], 24: [20, 21], 25: [22, 23], 28: [24, 25, 26, 27], 29: [28, 29], 30: [30, 31], 33: [32, 33, 34, 35], 34: [36, 37], 37: [38, 39], 38: [40, 41], 39: [42, 43, 44, 45], 40: [46, 47, 48, 49], 42: [50, 51], 43: [52, 53, 54, 55], 44: [56, 57], 46: [58, 59, 60, 61], 47: [62, 63], 48: [64, 65, 66, 67, 68, 69], 49: [70, 71], 50: [72, 73], 54: [74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85], 57: [86, 87], 58: [88, 89], 59: [90, 91], 60: [92, 93, 94, 95, 96, 97], 61: [98, 99], 62: [100, 101, 102, 103, 104, 105], 63: [106, 107, 108, 109, 110, 111], 64: [112, 113], 65: [114, 115, 116, 117], 67: [118, 119, 120, 121], 69: [122, 123], 70: [124, 125], 71: [126, 127, 128, 129, 130, 131], 72: [132, 133], 73: [134, 135, 136, 137], 74: [138, 139], 75: [140, 141], 76: [142, 143], 77: [144, 145, 146, 147], 78: [148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159], 79: [160, 161], 81: [162, 163], 85: [164, 165], 86: [166, 167], 87: [168, 169, 170, 171, 172, 173], 88: [174, 175, 176, 177], 93: [178, 179], 97: [180, 181], 98: [182, 183], 99: [184, 185], 101: [186, 187], 103: [188, 189, 190, 191], 113: [192, 193], 120: [194, 195], 126: [196, 197], 137: [198, 199]}

In [53]:
gr = df.groupby("Annual Income (k$)") ["Spending Score (1-100)"].agg(["sum","mean"])

In [54]:
gr

                    sum  mean
Annual Income (k$)
15                  120  60.0
16                   83  41.5
17                  116  58.0
18                  100  50.0
19                  188  47.0
...                 ...   ...
103                 194  48.5
113                  99  49.5
120                  95  47.5
126                 102  51.0
137                 101  50.5

[64 rows x 2 columns]

In [50]:
type(gr)

pandas.core.series.Series